### ISSUE TITLE
 dyld: malformed mach-o: load commands size (33848) > 32768

### ISSUE THREAD

**Issue by Fanxiaotsing** [dealii/dealii#10330]
All the examples can not run on macos catalina10.15.4 with 9.2.0 installed,can anyone  fix this problem?use the "otool -l"can get
otool -l /Applications/deal.II.app/Contents/Resources/Libraries/lib/libdeal_II.g.9.2.0.dylib 
/Applications/deal.II.app/Contents/Resources/Libraries/lib/libdeal_II.g.9.2.0.dylib:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           6   196      38368 0x00118085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __TEXT
   vmaddr 0x0000000000000000
   vmsize 0x0000000009087000
  fileoff 0
 filesize 151547904
  maxprot 0x00000005
 initprot 0x00000005
   nsects 7
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000000031260
      size 0x0000000006b90d33
    offset 201312
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0

@drwells edit: trimmed for brevity

**Comment by drwells** [comment]
This looks like a problem with our mac bundle. Let me see if I can replicate it.

**Comment by drwells** [comment]
@luca-heltai I can reproduce this issue on my mac (a week-old mac mini running Catalina). Let me know when you are available to take a look.

**Comment by luca-heltai** [comment]
Unfortunately, I cannot reproduce on my mac. We could take a look at this today?

**Comment by Fanxiaotsing** [comment]
So that means I have to build the library from the bottom?

**Comment by drwells** [comment]
Unfortunately, until we get this fixed that will be necessary.

**Comment by drwells** [comment]
@luca-heltai I have time to fix this but I don't know how to build or test the mac bundle. Could you help me by pointing me to instructions on how to rebuild the mac bundle with spack on my machine?

**Comment by luca-heltai** [comment]
I've tried to fix this in the past week, with no luck. The way I proceed is the following: 

1. I create the directory

/Applications/deal.II.app/Contents/Resources/

2. in that directory, I clone the spack repository. Now you have

/Applications/deal.II.app/Contents/Resources/spack

Call this SPACK_ROOT

3. somewhere in the path I download and expand a version of gfortran (i.e., 

$SPACK_ROOT/gcc-9.2

for example, from http://prdownloads.sourceforge.net/hpc/gfortran-9.2-bin.tar.gz?download)

4. I run the https://gist.github.com/luca-heltai/d52952a8c6334a1c5374bd96fb165c08#file-relocate_libraries-py script in that directory, so that gfortran is correctly relocated (with absolute paths)

5. I make sure spack knows about gfortran 

$SPACK_ROOT/bin/spack compiler add --scope site $SPACK_ROOT/gcc-9.2

6. I modify 

$SPACK_ROOT/etc/spack/compilers.yaml

so that clang and gcc-9.2 are both present as cxx and gfortran compilers:

```
compilers:
- compiler:
    spec: clang@11.0.3-apple
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /Applications/deal.II.app/Contents/Resources/spack/gcc-9.2/bin/gfortran
      fc: /Applications/deal.II.app/Contents/Resources/spack/gcc-9.2/bin/gfortran
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {unset: []}
    extra_rpaths: []
```

7. Now run 

$SPACK_ROOT/bin/spack install dealii@9.2

If this succeeds, you should be able to run deal.II examples. After this, we can make a bundle by filling the rest of the`app` directory.
