### ISSUE TITLE
Linker error 9.2.0 dmg on MacOS Catalina: argument list too long

### ISSUE THREAD

**Issue by anne-glerum** [dealii/dealii#11138]
As I mentioned in the closed issue #10656, I'm experiencing linker errors when trying to install ASPECT. Could this be related to the very long directory names?

With the current dealii image on Catalina, after `module load dealii`, I try to install ASPECT and get the following linker error:
`[114/114] Linking CXX executable aspect`
`FAILED: aspect `
`: && /Applications/deal.II.app/Contents/Resources/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/openmpi-3.1.6-ch3xlssbdriiio4hygk3xhnxclncjvze/bin/mpic++` + ...a very long list...
`clang: error: unable to execute command: posix_spawn failed: Argument list too long`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`ninja: build stopped: subcommand failed.`

_Originally posted by @anne-glerum in https://github.com/dealii/dealii/issues/10656#issuecomment-712726901_

**Comment by drwells** [comment]
I think no one commented in the previous thread because few of us use the mac bundle and fewer of us use it with ASPECT (speaking for myself, at least, I don't use spack or the bundle).

`posix_spawn` is a low-level enough function that I suspect there is no easy fix. @luca-heltai do you have any hints?

**Comment by drwells** [comment]
I would much rather fix the mac bundle but a possible workaround is to just https://github.com/dealii/candi - does that at least get things working for you?

**Comment by anne-glerum** [comment]
Unfortunately I had compiler issues with candi that I couldn't sort out with the help of @tjhei, so I decided to try the bundle.

**Comment by drwells** [comment]
@luca-heltai even if you don't have time to fix this, could you pass along the code you have for setting up the mac package so we can take a look?

**Comment by drwells** [comment]
Timo, JP, and I are talking about this now and some possible fixes. We think we can fix the very long package names by modifying `config:install_tree:projections:all`. See 

https://spack.readthedocs.io/en/latest/config_yaml.html

**Comment by luca-heltai** [comment]
There is nothing special to do: install the package, then call `spack uninstall *`, modify the parameters, and call `spack install dealii` again (maybe after updating spack to the last version). If this works, `spack clean all`, and then copy the `deal.II.app` into a copy of the dmg file. If you don't know/don't want to do these last steps, I can easily do them for you, once you have a working `deal.II.app`. Just send me a compressed copy of the `spack` tree.

**Comment by luca-heltai** [comment]
I'll try to do this later today.

**Comment by tjhei** [comment]
Great, thank you @luca-heltai . Can I ask you to consider adding ``module load dealii`` by default when opening the deal.II terminal? This has been difficult for many new users as things "mostly" work until you try to link ASPECT.

Finally, it would be great to have a script to generate the .dmg that is reproducible and available somewhere. But one step at a time. :-)

**Comment by luca-heltai** [comment]
The "script" is 

`rm -rf /Volumes/deal.II.dmg/deal.II.app/; cp -a /Applications/deal.II.dmg/deal.II.app/  /Volumes/deal.II.dmg/deal.II.app/`

:) 

btw, I'm having difficulties in building scalapack. It simply won't build with the latest XCode.

I did not add the `module load dealii` by default because it takes a few seconds to complete and I found it annoying, but sure, no problem. That can be done (once compilation of scalapack succeeds).

Did any of you succeeded in building scalapack and/or petsc without it?

**Comment by tjhei** [comment]
> The "script" is

I doubt that this is it, what about creating directories, cloning spack, installing deal.II, adding the files, etc.?

> I did not add the `module load dealii` by default because it takes a few seconds to complete and I found it annoying, but sure, no problem.

I don't see why the deal.II terminal is useful without running the module load command. Annoying that this is slow...

> btw, I'm having difficulties in building scalapack.

If you want to post details, @jppelteret might be able to help.

**Comment by jppelteret** [comment]
This is my current `package.yaml` file. I see that I have scalapack disabled, so I think that I must have also hit difficulties with it (and ADOL-C too) :-/ I'll try to install it again to see what's going on and if there's anything that can be done within the spack ecosystem to fix it.
```
packages:
  all:
    compiler: [apple-clang, gcc, clang]
    providers:
      mpi: [openmpi]
      blas: [openblas]
      lapack: [openblas]
  dealii:
    version: [master]
    variants: ~adol-c+arpack+assimp~cuda~doc~examples~ginkgo+gmsh+gsl+hdf5~int64+metis+mpi+muparser~nanoflann~netcdf+oce+optflags+p4est+petsc~python~scalapack+slepc+sundials+symengine+threads+trilinos
  boost:
    version: [1.72.0]
  gcc:
    version: [9.3.0]
  llvm:
    version: [9.0.1]
  openmpi:
    version: [3.1.6]
  trilinos:
    variants: ~exodus~netcdf~pnetcdf~mumps
  symengine:
    variants: +llvm
```
