### ISSUE TITLE
CHECK_CXX_SOURCE_COMPILES does not use the correct compile flags.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#18248]
@tamiko This is an issue I need your help with.

The underlying cause I'm trying to resolve is that libc++ (clang's C++ library) does not implement `std::cyl_bessel_j`. We test this with the following piece of code in `cmake/checks/check_01_cxx_features`:
```
#
# Check for c++17 Bessel function support. Unfortunately libc++ version 10
# does not have those.
#

CHECK_CXX_SOURCE_COMPILES(
  "
  #include <cmath>
  using std::cyl_bessel_j;
  using std::cyl_bessel_jf;
  int main()
  {
  }
  "
  DEAL_II_HAVE_CXX17_BESSEL_FUNCTIONS
  )
```

The problem is the following. Let's say I do this:
```
export CXXFLAGS="-stdlib=libc++"
export CXX=clang++
cmake ../dealii
```
Then if you go to `CMakeFiles/CMakeConfigureLog.yaml` and search for BESSEL, you will find an entry like this:
```
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/usr/share/cmake-3.28/Modules/CheckCXXSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "cmake/checks/check_01_cxx_features.cmake:615 (CHECK_CXX_SOURCE_COMPILES)"
      - "cmake/macros/macro_verbose_include.cmake:18 (include)"
      - "CMakeLists.txt:123 (verbose_include)"
    checks:
      - "Performing Test DEAL_II_HAVE_CXX17_BESSEL_FUNCTIONS"
    directories:
      source: "/home/bangerth/p/deal.II/2/build-test/CMakeFiles/CMakeScratch/TryCompile-OTSmON"
      binary: "/home/bangerth/p/deal.II/2/build-test/CMakeFiles/CMakeScratch/TryCompile-OTSmON"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/usr/bin/clang-scan-deps-18"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: ""
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/bangerth/p/deal.II/2/cxx-modules/cmake/modules/"
    buildResult:
      variable: "DEAL_II_HAVE_CXX17_BESSEL_FUNCTIONS"
      cached: true
      stdout: |
        Change Dir: '/home/bangerth/p/deal.II/2/build-test/CMakeFiles/CMakeScratch/TryCompile-OTSmON'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_929cc/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_929cc.dir/build.make CMakeFiles/cmTC_929cc.dir/build
        gmake[1]: Entering directory '/home/bangerth/p/deal.II/2/build-test/CMakeFiles/CMakeScratch/TryCompile-OTSmON'
        Building CXX object CMakeFiles/cmTC_929cc.dir/src.cxx.o
        /usr/bin/clang++ -DDEAL_II_HAVE_CXX17_BESSEL_FUNCTIONS  -pedantic -Werror -Wno-unused-command-line-argument -std=c++17 -MD -MT CMakeFiles/cmTC_929cc.dir/src.cxx.o -MF CMakeFiles/cmTC_929cc.dir/src.cxx.o.d -o CMakeFiles/cmTC_929cc.dir/src.cxx.o -c /home/bangerth/p/deal.II/2/build-test/CMakeFiles/CMakeScratch/TryCompile-OTSmON/src.cxx
        Linking CXX executable cmTC_929cc
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_929cc.dir/link.txt --verbose=1
        /usr/bin/clang++  -pedantic -Werror -Wno-unused-command-line-argument CMakeFiles/cmTC_929cc.dir/src.cxx.o -o cmTC_929cc 
        gmake[1]: Leaving directory '/home/bangerth/p/deal.II/2/build-test/CMakeFiles/CMakeScratch/TryCompile-OTSmON'
        
      exitCode: 0
```
So it detects the presence of `std::cyl_bessel_j`, *but that is because it calls Clang without the `-stdlib=libc++` flag*. So it looks for the presence of that function in libstdc++ (the GCC library) where it is correctly implemented, even though we want to know whether it's in libc++.

I have no idea where this needs to be addressed, but it's clearly a bug in our detection machinery.
